name: 02 - Workflow Filtro

on:
    push:
        branches: 'feature/**'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: exibir evento
              run: echo"workflow disparado por${{ github.event_name }}